- oxygen.md
Added github author affiliation for BYQ
> Added github author affiliation for BYQ

- oxygen.bib
> Reference added

- oxygen.md
> I changed the logo in the text

- oxygen.md
> updated my affiliation

- oxygen.md
> made a NOTE italic

- README.md
> reformatted license section

- oxygen.md
correcting some typos in oxygen.md
> correcting some typos in oxygen.md

- oxygen.md
I just reviewed the DMQC chapter and corrected a few small typos, format issues.
> correcting typos, formatting in DMQC

- oxygen.md
> added GKrahmann github page

- oxygen.md
I added a first draft for sampling frequency.
> add sampling frequency

- README.md
https://github.com/OceanGlidersCommunity/Oxygen_SOP/blob/main/oceangliders_oxygen_sop_v0.pdf
> add link to recent v0 pdf

- CONTRIBUTING.md
I added a first draft for a decision making process for the oxygen SOP, which could also guide the other SOPs.
I now also distinguish between making a comment by raising an issue (Case 1) and making a concrete suggestion to the text via a pull-request (Case 2).
Could everyone read the whole guide and comment?
> [WIP] decision making

- .github/workflows/build_book.yml
Using the main not master naming.
> Fix main branch in build book

- _config.yml
@jbusecke I am preparing the refereeing. Could you please review?
> add bibtex file oxygen.bib

- images/permissions.md
Update information for images 3,7,17,24, 26
> Update information for images 3,7,17,24, 26

- sections/oxygen_pre_deployment.md
Trying again to add Garcia-Robledo2021 after correcting the oxygen.bib file
> add Garcia-Robledo2021 

- sections/oxygen_mission_execution.md
Update section Deploying gliders in Oxygen Minimum Zones (OMZ) to match previuos section (Two point calibration procedure, optode example).
Changed uM for $\mu$mol/kg
> Update Deploying gliders in Oxygen Minimum Zones

- sections/authors_SOP_development_process.md
adding @s-pearce authorship and contributions
> adding Stuart Pearce authorship and contributions

- sections/oxygen_pre_deployment.md
This relates to #94 
cleaning: also remove some old comments in the text
> try to fix numeration

- sections/oxygen_sensors_integration.md
> SVU optode version

- sections/authors_SOP_development_process.md
@pipa85 is this fine for you? Please check and update your contributions accordingly.
> add Filipa Carvaho as co-author

- sections/authors_SOP_development_process.md
As someone measuring in the Southern Ocean Isabelle will try to support us with filling the gab for oxygen measurements at very low temperatures and support technical maintenance of the SOP here on GitHub. Thanks @isgiddy 
PS: please also check out the Salinity SOP she is leading, we have started the community review.
> add Isabelle Giddy as co-author

- README.md
After discussing with @paulineobps from OBPS we now will first deposit a version 1.0 to the OBPS, get a doi there and publish a shorter version in Frontiers.
> update order of process

- sections/oxygen_sensors_integration.md
small notes and some updates to unicode.
> optode svu version

- sections/authors_SOP_development_process.md
@evibourma is this your ORCID ID?
0000-0001-7196-9714
> add Evi Bourma's ORCID

- sections/oxygen_mission_execution.md
The figure is more related with all deployments and activties during them not only for activities when deploying from a small boat.
> Moved Fig 5.1 to section 5.1

- sections/authors_SOP_development_process.md
> add Christian Begler as co-authors

- sections/oxygen_sensors_integration.md
Thanks @gkrahmann and Christian Begler for providing this new image. Gerd could you check whether the figure caption is still correct? Is this an Aanderaa optode 4831?
> update image Slocum Optode

- sections/oxygen_mission_execution.md
Feel free to accept/reject them :)
> Corrected some typos

- sections/oxygen_sensors_integration.md
Feel free to accept them or reject them :)
> Corrected some typos int he text

- sections/oxygen_rtqc.md
Feel free to reject/accept them :)
At the end of section 6.1 there is a reference to a paragraph but no link, do we need to remove it? Or there is a document we can reference to?
I deleted reference to Fig 7.1 at the end of the last section, I think the diurnal cycle is not related with it?
> Typos corrected

- sections/oxygen_mission_execution.md
- sections/oxygen_sensors_integration.md
some spelling fixes and closes #143
> standardise dphase and calphase

- sections/oxygen_mission_execution.md
> keep 8 h -> 24 h wet before deployment

- sections/acknowledgement.md
- sections/authors_SOP_development_process.md
- sections/oxygen_appendix.md
- sections/oxygen_dmqc.md
- sections/oxygen_introduction.md
- sections/oxygen_mission_execution.md
- sections/oxygen_pre_deployment.md
- sections/oxygen_rtqc.md
- sections/oxygen_sensors_integration.md
Fixes for English language use following Oxford conventions. Spellings corrected and other small formating changes.
> apply oxford english language, markdown linting

- .github/workflows/build_book.yml
Attempt to address concern in #229, that builds take long due to pdf generation.
> Only build pdf on release

- sections/authors_SOP_development_process.md
@patricialg or @tomhull we now have the official GOOS endorsement also mentioned in the OBPS so I update the process page please review
> add GOOS endorsement

- requirements.txt
Trying the same as https://github.com/OceanGlidersCommunity/Salinity_SOP/pull/139/files
> Fix for utterances

- sections/authors_SOP_development_process.md
Thanks @callumrollo for your support in maintaining the SOPs. This is key for them to fly long term. 
Please adapt your contributions. 
Note that we are writing a summary paper for Frontiers. @tomhull @patricialg are leading this work and are happy to have fresh support!
Before we submit the Frontiers paper we have to ensure to make a new release v1.1.X or so submit it to OBPS to ensure to have you as co-author!
> add callums contribution

- sections/oxygen_rtqc.md
@tomhull, @cgourcuf, @patricialg  could you review my implementation of your suggestions. 
This addresses: #238
FYI @vturpin
> content: rewriting of "recommended corrections"

- requirements.txt
as discussed here: https://github.com/OceanGlidersCommunity/DepthAverageCurrents_SOP/pull/123
> restrict to pybtex-apa-style>=1.3

- .github/workflows/build_book.yml
This should reduce some warnings during building of the book.
> update GitHub actions / setup-python@v1 - 4

- .github/workflows/build_book.yml
- .github/workflows/preview-book.yml
This PR aims to update GitHub actions to get rid of all warnings related to Node16
> update github actions, prepare for Node16
